NON_DATE_COLUMNS = {
    "Employee ID",
    "Employee Full Name",
    "Position",
    "Project",
    "Is Flagged",
    "Notes",
    "Total Work Hours",
    "Overtime",
    "Holiday Premium",
    "Rate",
    "Allowance",
    "PHIC",
    "Others",
    "HDMF",
    "SSS",
}
