"""make employee_id unique with project

Revision ID: 12c02e19b130
Revises: 5f36d4cd8c19
Create Date: 2026-07-21 12:40:53.787847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c02e19b130'
down_revision: Union[str, Sequence[str], None] = '5f36d4cd8c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_employee_id_key'), 'employees', type_='unique')
    op.create_unique_constraint('uq_employee_id_project', 'employees', ['employee_id', 'project'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_id_project', 'employees', type_='unique')
    op.create_unique_constraint(op.f('employees_employee_id_key'), 'employees', ['employee_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
