"""add others field to employee payroll_record and payslip

Revision ID: 646a1bd90071
Revises: 716cda5d777a
Create Date: 2026-08-18 02:41:45.803150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646a1bd90071'
down_revision: Union[str, Sequence[str], None] = '716cda5d777a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows to 0, then gets dropped so the
    # column behaves like sss/hdmf/phic: NOT NULL with no default, always
    # supplied explicitly by the application.
    op.add_column(
        'employees',
        sa.Column('others', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'),
    )
    op.alter_column('employees', 'others', server_default=None)
    op.add_column(
        'payroll_records',
        sa.Column('others', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'),
    )
    op.alter_column('payroll_records', 'others', server_default=None)
    op.add_column(
        'payslips',
        sa.Column('others', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'),
    )
    op.alter_column('payslips', 'others', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payslips', 'others')
    op.drop_column('payroll_records', 'others')
    op.drop_column('employees', 'others')
    # ### end Alembic commands ###
