"""add holidays payroll periods records attendance days and payslips

Revision ID: 716cda5d777a
Revises: 6b99a3fe8b12
Create Date: 2026-08-17 02:22:45.838054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716cda5d777a'
down_revision: Union[str, Sequence[str], None] = '6b99a3fe8b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('payroll_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_date', 'end_date', name='uq_payroll_period_dates')
    )
    op.create_table('payroll_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_period_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('total_work_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allowance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sss', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hdmf', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('phic', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_period_id', 'employee_id', name='uq_payroll_record_period_employee')
    )
    op.create_table('attendance_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_record_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('work_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_record_id', 'date', name='uq_attendance_day_record_date')
    )
    op.create_table('payslips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_record_id', sa.UUID(), nullable=False),
    sa.Column('payroll_period_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('total_work_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allowance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sss', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hdmf', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('phic', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_holiday_pay_eligible', sa.Boolean(), nullable=True),
    sa.Column('holiday_date', sa.Date(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payslips')
    op.drop_table('attendance_days')
    op.drop_table('payroll_records')
    op.drop_table('payroll_periods')
    op.drop_table('holidays')
    # ### end Alembic commands ###
